### ISSUE TITLE
Next release: text to be changed

### ISSUE THREAD

**Issue by sayanarijit** [rapidstack/RESTEasyCLI#2]
https://github.com/rapidstack/RESTEasyCLI/blob/e3671145aced84f97b636bce20d82122fd21b743/resteasycli/lib/abstract_finder.py#L30

Should be "searching for file: filepath"

**Comment by sayanarijit** [comment]
Raise the pull request

**Comment by sayanarijit** [comment]
Also, for future modifications, instead of creating new branch, it's better to fork this repo as personal repository and create pull request from it. This way this repo will be cleaner.

**Comment by suryasr007** [comment]
Ok, Raised pull request.
