### ISSUE TITLE
[BUG] windows compatibility

### ISSUE THREAD

**Issue by sayanarijit** [rapidstack/RESTEasyCLI#3]
Windows compatibility needs to be fixed.

**Comment by suryasr007** [comment]
@sayanarijit 
Are u working on this?

**Comment by suryasr007** [comment]
Hi @sayanarijit 

I have tested in windows. Its working fine for todos as well as below api.

(venv) PS D:\Github\RESTEasyCLI> recli get random_password/generate
{
  "password": "Oi1qIu?"
}

What is the bug?

**Comment by sayanarijit** [comment]
Great... I think issue was due to python3.7 incompatibility.
Closing this.
