### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by iamTheL** [rapidstack/RESTEasyCLI#46]
As per your [documentation](https://resteasycli.readthedocs.io/en/latest/) this package works only on *nix machines.

Are you planning to make this available for windows ?

**Comment by suryasr007** [comment]
@iamTheL 

This has been addressed by #3 . Is it what you are referring to ?

**Comment by sayanarijit** [comment]
Hi @iamTheL 
As @suryasr007 pointed out, script is already Windows compatible.
Only the [interactive demo](https://github.com/rapidstack/RESTEasyCLI/blob/master/tools/demo.sh) is supposed to be windows incompatible. Right now I am not planning to create a windows specific demo as rapid changes are being done on regular basis and it will be difficult to test the demo on windows till we reach a stable version. Anyway this script targets mainly terminal users, majority of them are *nix users.
