### ISSUE TITLE
Add syntax verifierfor workspace files

### ISSUE THREAD

**Issue by sayanarijit** [rapidstack/RESTEasyCLI#7]
Add syntax verifier for workspace files

**Comment by suryasr007** [comment]
@sayanarijit 
Are you referring to something like [pyflakes](https://github.com/PyCQA/pyflakes)?

**Comment by sayanarijit** [comment]
No... It will check if sites.yml, auth.yml etc. are written correctly. Like `visudo -cf`.
It will execute before *workspace* object loads and makes sure there is no mistake from user end. It should cover as much as possible.
It should follow the rule based pattern with each rule as a separate class having `verify()` method that takes the data to be verified as argument and throws InvalidEntryException when incorrect entry found. There will be seperate set of rules for each file; however, some rules may be common for all the files.

**Comment by sayanarijit** [comment]
Change of plan. instead of checking all the files, *workplace* object will load a verifier only when needed to avoid unnecessary computation.

**Comment by sayanarijit** [comment]
We can easily handle this using marshmallow. For that we just need to create a bunch of schemas and tell workspace to validate data using it after reading files or when `get_site` or `get_auth` etc are invoked.

**Comment by sayanarijit** [comment]
I'll work on saved requests validation.

**Comment by sayanarijit** [comment]
I'll to the sites file next

**Comment by sayanarijit** [comment]
All done

**Comment by suryasr007** [comment]
> All done

😅 😅
